version: '3.9'

services:
    app:
        build: './'
        ports:
            - '8181:8181'

    mongodb:
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - ${DB_PORT}:27017
